version: '3.8'

services:
  payments-stripe:
    build:
      context: ./services/payments-stripe
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    env_file:
      - .env
    volumes:
      - ./services/payments-stripe:/app
      - /app/node_modules
    depends_on:


  file-storage:
    build:
      context: ./services/file-storage
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
    env_file:
      - .env
    volumes:
      - ./services/file-storage:/app
      - /app/node_modules
    depends_on:


  database-postgres:
    build:
      context: ./services/database-postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - NODE_ENV=development
      - PORT=5432
    env_file:
      - .env
    volumes:
      - ./services/database-postgres:/app
      - /app/node_modules
    depends_on:
      - postgres

  queue-redis:
    build:
      context: ./services/queue-redis
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - PORT=3008
    env_file:
      - .env
    volumes:
      - ./services/queue-redis:/app
      - /app/node_modules
    depends_on:
      - redis

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    depends_on:


  cache-redis:
    build:
      context: ./services/cache-redis
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
    env_file:
      - .env
    volumes:
      - ./services/cache-redis:/app
      - /app/node_modules
    depends_on:
      - redis

  notifications:
    build:
      context: ./services/notifications
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    env_file:
      - .env
    volumes:
      - ./services/notifications:/app
      - /app/node_modules
    depends_on:


  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppassword
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
